services:
  - type: web
    name: telegram-video-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: CHANNELS
        sync: false
      - key: PORT
        value: 5000
